#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_DIALOG1                             100
#define IDC_LIST1                               1000
#define IDC_BUTTON1                             1001
#define IDC_BUTTON2                             1002
#define IDC_LIST2                               1003
#define IDC_BUTTON3                             1004
#define IDC_BUTTON4                             1005
#define IDC_BUTTON5                             1006
#define IDC_BUTTON6                             1007
#define IDC_BUTTON7                             1008
#define IDC_EDIT1                               1009
#define IDC_EDIT2                               1010
#define IDC_BUTTON8                             1011
#define IDC_BUTTON9                             1012
#define IDC_WIDTH1                              1014
#define IDC_NUM1                                1015
#define IDC_BUTTON11                            1016
#define IDC_SLIDER1                             1017
#define IDC_SLIDER2                             1018
#define IDC_STATIC1                             1019
#define IDC_STATIC2                             1020
#define IDC_WIDTH                               1021
#define IDC_HEIGHT                              1022
#define IDC_HEIGHT1                             1023
#define IDC_NUM2                                1024
#define IDC_NUM3                                1025
#define IDC_BUTTON15                            1026
#define IDC_GRID                                1027
#define IDC_SGRID                               1028
#define IDC_NUM                                 1029
#define IDC_BUTTON12                            1030
#define IDC_BUTTON16                            1031
#define IDC_PICK                                1032
#define IDC_BUTTON13                            1033
#define IDC_BUTTON14                            1034
#define IDC_PICK1                               1035
#define IDC_BUTTON17                            1037
#define IDC_BUTTON18                            1038
#define IDC_EDIT3                               1039
#define IDC_BUTTON10                            1040
